name: Bug Report
description: File a bug report
title: '[App/Bug]: '
labels: ['app', 'bug']
projects: ['xKesvaL/5']
assignees:
  - xkesval
  - gbihry
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe Bug
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to do X, and Y happened instead.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: PLease describe the steps to reproduce the behavior.
      placeholder: |
        1. Go to the LeetStrength application 
        2. Click on '....' 
        3. Scroll down to '....' 
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        I expected to see ..., but instead I saw ...
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: input
    id: platform
    attributes:
      label: Platform
      description: |
        Please specify the platform you are using and its version.
        For example: Windows 10, MacOS, Linux, Android, iOS, etc.
      placeholder: |
        Windows 10
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Application Version
      description: |
        Please specify the version of the application you are using.
        For example: 1.0.0, 1.0.1, 1.1.0, etc.
      placeholder: |
        1.0.0
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: |
        Please specify the browser you are using if you are using the web application.
        For example: Chrome, Firefox, Safari, Edge, etc.
      placeholder: |
        Chrome
