name: Bug Report
description: File a bug report
title: '[App/Bug]: '
labels: ['app', 'feature request']
projects: ['xKesvaL/5']
assignees:
  - xkesval
  - gbihry
  - thibaudrtz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature request!
  - type: textarea
    id: describe
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: would-like
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
        While this field is optional, it is strongly recommended that you fill it out.
        If you do, the feature request will be more likely to be accepted.
      placeholder: |
        I expected to see ..., but instead I saw ...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        You can drag your video or image files inside of this editor ↓
