name: CI Tests

on:
  push:
    branches:
      - main
      - dev

permissions: {}
jobs:
  format:
    runs-on: ubuntu-latest
    name: Formatting Code
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: "pnpm i && pnpm format"

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Linting Tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: "pnpm i && pnpm lint"
